services:
  app:
    build: .
    container_name: chango_app
    ports:
      - "8080:8080"
    environment:
      # IMPORTANTE: Dentro de Docker, no usamos 'localhost', usamos el nombre del servicio
      - DB_URL=postgres://chango_user:chango_password@postgres:5432/chango_app
      - REDIS_ADDR=redis:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    container_name: chango_db
    environment:
      POSTGRES_USER: chango_user
      POSTGRES_PASSWORD: chango_password
      POSTGRES_DB: chango_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: chango_cache
    ports:
      - "6379:6379"

volumes:
  postgres_data: