services:
  postgres:
    image: postgres:15
    container_name: chango_db
    environment:
      POSTGRES_USER: chango_user
      POSTGRES_PASSWORD: chango_password
      POSTGRES_DB: chango_app
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: chango_redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: chango_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./ui/static/avatars:/app/ui/static/avatars # IMPORTANTE: Para que no se borren las fotos